### ISSUE TITLE
江心人Blog任务反馈

### ISSUE THREAD

**Issue by raytaylorlin** [ITEC-ELWG/FE-Study#105]
页面和代码干净整洁，不错。功能上，登录页的“GO”按钮链向了一个不存在的页面，其余代码问题如下：
- `index.html`中缺body和html的闭合标签，以及有一点细小的语法错误。注意浏览器在解析HTML时通常不会报语法错，而是会尝试着去解析，但最好还是要规范避免被解析错
- HTML中不要给`<img>`标签指定宽高，宽高样式应在CSS中指定

**Comment by Kannnnng** [comment]
任务过期，清理关闭
