### ISSUE TITLE
蔡孝直Blog任务反馈

### ISSUE THREAD

**Issue by raytaylorlin** [ITEC-ELWG/FE-Study#115]
首页文章列表部分，并不符合水平居中要求，需要修改
#### 布局问题
- `<div>`用得过多，这是初学者经常遇到的问题，**并不是**每一个标签（例如input、p、a等等））都要在外层套上一层wrapper，应该遵循HTML标签的语义
- 思考：首页两栏式布局，虽然用相对定位在视觉上可以满足要求，但这不是最佳方案，请查找更通用的两栏式布局方案
- 思考：虽然用了各种相对定位和绝对定位在视觉上可以满足定位到中间的要求，但代码中毕竟要加上负的定值margin来偏移，这种定位方式在容器不是定宽和定高的情况下就行不通，请查找更通用的居中解决方案

**Comment by Kannnnng** [comment]
任务过期，清理关闭
