### ISSUE TITLE
孔思聪BLOG（PHP）任务反馈

### ISSUE THREAD

**Issue by NeoyeElf** [ITEC-ELWG/FE-Study#131]
1. 缺少.sql文件
2. cookie未起作用，仍能直接访问index.php；不要将account存入cookie，只存每个人的id就行
3. 为对输入的空数据作处理
4. 数据库连接不上时，用try，catch捕获异常，不要直接显示php错误
5. 注册时未对插入数据库的数据进行过滤
6. 不要明文传递密码

**Comment by NeoyeElf** [comment]
1. 数据库和表字段的字符集不正确，用utf8mb4
2. 字段类型不正确，'account','password','name'用varchar类型，text是用来存储长文本的
3. 未登陆输入index.php，会停留在首页一会才跳转，而且首页有php error
4. 登陆时，输入信息错误，没有提示，而且当点击登录时，密码栏会闪烁md5后的密码值
5. 注册时传递的repassword是明文
6. 你在登录和注册时传submit参数是干嘛的？
7. 输入正确的用户名，密码，无法登录

**Comment by Kannnnng** [comment]
任务过期，清理关闭
