### ISSUE TITLE
蔡孝直BLOG(PHP)任务反馈

### ISSUE THREAD

**Issue by NeoyeElf** [ITEC-ELWG/FE-Study#139]
1. test表里没有自增主键id，不要把username设为PRIMARY KEY
2. 建立数据库时，默认的编码未设置为utf-8
3. 你干嘛要求别人密码为数字？
4. 点击注册按钮无法进入注册页面
5. 直接显示了php错误信息，未做try,catch处理

**Comment by Kannnnng** [comment]
任务过期，清理关闭
