### ISSUE TITLE
王佳静任务反馈

### ISSUE THREAD

**Issue by raytaylorlin** [ITEC-ELWG/FE-Study#154]
### Blog任务反馈

主页的功能基本没问题，但是登录页并不符合居中要求（用ctrl+鼠标滚轮缩放一下，你就能发现问题）
#### HTML问题
- 缺少doctype文档头
- 不要使用table来布局！具体为什么，请参照[Stackoverflow: Why not use tables for layout in HTML?](http://stackoverflow.com/questions/83073/why-not-use-tables-for-layout-in-html)及网上其他资料
- 你确定有`<h7>`这种HTML标签？
- 尽量不要使用`<br/>`来留白或空行，这都是一个margin样式就可以搞定的事情
#### CSS问题
-  布局和定位几乎全靠width、height、margin+绝对的像素值来完成，这样的布局兼容性很差（这种做法其实和绝对定位没啥区别）
- 尽量不要使用id选择器来设置样式
- 既然要用id选择器，那就纯用id选择器就可以了，`div#login`的div完全是多余的
- CSS class和id命名要更加规范一些，像`#h5`这种既含糊，又没必要；其他不知其义的命名，诸如`.r1`、`.a_list`等等均不可取
- CSS class命名前后不统一，有的用了下划线形式如`.p_copyright`，有的用了camel命名法如`loadBtn`。推荐用中划线分隔单词的形式，如`.menu-list`
#### 其他问题
- 本任务仅使用标准HTML和CSS已经足够，不需要Javascript甚至jQuery。本任务中，点击跳转只需要做个超链接就够了
- 在没有熟练掌握基础的CSS的时候，为什么要使用预处理器Sass（即`.scss`文件）？既然要用Sass，那使用到Sass的特性了吗？
- Git版本控制推崇细粒度提交，请不要一口气commit过多的文件，至于为什么，可以看看[这个](http://weibo.com/p/1001603791680464653659?from=page_100505_profile&wvr=6&mod=wenzhangmod&sudaref=www.google.com)

**Comment by missMHWGO** [comment]
* 发现问题了。。。可是改成相对布局好像也不行。。。
### HTML
*  `<h7>`是我自己定义的。。。
### CSS
* 那一般用相对布局对吗？不能用像素值吗？
###其他问题
* 可是直接跳转不能做验证啊~
* 主要是想用嵌套。。。
* 我只是提交了一个作业呀~以后要一个文件一个文件交吗。。。
###谢谢~~~

**Comment by missMHWGO** [comment]
* 发现问题了。。。可是改成相对布局好像也不行。。。
### HTML
*  `<h7>`是我自己定义的。。。
### CSS
* 那一般用相对布局对吗？不能用像素值吗？
###其他问题
* 可是直接跳转不能做验证啊~
* 主要是想用嵌套。。。
* 我只是提交了一个作业呀~以后要一个文件一个文件交吗。。。
###谢谢~~~

**Comment by missMHWGO** [comment]
* 发现问题了。。。可是改成相对布局好像也不行。。。
*  `<h7>`是我自己定义的。。。
* 那一般用相对布局对吗？不能用像素值吗？
* 可是直接跳转不能做验证啊~
* 主要是想用嵌套。。。
* 我只是提交了一个作业呀~以后要一个文件一个文件交吗。。。
* 谢谢啦~~~

**Comment by missMHWGO** [comment]
### 井号
### 井号

**Comment by raytaylorlin** [comment]
> `<h7>`是我自己定义的

自己定义的标签没有任何用途，浏览器只管标准的标签

> 可是直接跳转不能做验证

这个任务只是让你熟悉最基础的HTML和CSS布局，不用想那么复杂，要考虑验证实际上在任务4中有

> 我只是提交了一个作业呀~以后要一个文件一个文件交吗

git推荐的细粒度提交并不是要你一个文件一个文件提交，而是你完成了一件事，就可以提交一次，并**写清楚log说明你这次提交做了什么事情**，比如“搭建页面骨架”，“完成页面基础上中下布局”，“完成登录页面”，“修复登录页面没有居中的问题”，等等

> 那一般用相对布局对吗？不能用像素值吗？

可以用像素值，但不是你那样滥用，建议你看看其他人的代码参考学习。（之所以把大家的代码放在Github上，就是让你们互相学习的）

* [wangrui blog](https://github.com/ITEC-ELWG/FE-Study/tree/master/wangrui/blog)
* [yangnan blog](https://github.com/ITEC-ELWG/FE-Study/tree/master/yangnan/Blog)

**Comment by raytaylorlin** [comment]
### Calculator任务反馈

#### 功能问题

* 输入“1+2+3+4+5=”，显示“6”，推测是你取了头尾的数做计算？两种解决方案，要么改为真正去计算一个完整的表达式，要么改为像市面普通计算器一样，屏幕上只会显示一个数字，**不会**显示运算符，每次取最后两个数字做计算（随便找一个最普通的计算器看看什么样的）

#### 代码问题

* 有部分tab和空格混排的情况，请统一全部使用4空格缩进
* .null, .symbol, .num, .dot, .equal这5个类共用的一段CSS，这表明这5种类其实有共同的东西，只用一个类来表示，并换一个能代表5个类共性的名字，就够了
* `equal[0]`, `symbol[3]`等等可读性较差
* 函数命名不贴切。你的每一个函数基本上都是在绑定事件，例如`calculate()`，其他人调用此函数期待的是**计算出结果**，但实际上调用了之后什么也没发生。建议重构成下面这个样子：

```
var bindCalculate = function() {
    equal[0].onclick = calculate;
};

function calculate() {
    // 真正的计算逻辑
}
```

**Comment by missMHWGO** [comment]
#功能问题
* 我只做了两个数的计算，按照我实现的逻辑，确实是只会取第一个数和最后一个数的。。。我再改改~

#谢谢~O(∩_∩)O~

**Comment by raytaylorlin** [comment]
### Puzzle8任务反馈

#### 功能问题

* Reset按钮没有效果，点击后应该根据输入的数字n（注意判断n的合法性），生成n*n的棋盘
* 每次刷新生成的棋盘的缺口都在右下角，实际上缺口应该也是随机出现

#### 代码问题

* 参照#136 最后一条评论反馈，在实际使用当中要尽量避免反复进行$(“.block")和$(".move")这样的耗性能的操作
* 函数命名，诸如`getrandomshow`没有遵循camel命名法，应该是`getRandomShow`
* `innerHTML`是原生JS的写法，既然用了jQuery，那就使用同等效果的jQuery API来实现吧

**Comment by raytaylorlin** [comment]
#161 Blog任务完成
#163 Calculator任务完成

**Comment by raytaylorlin** [comment]
#171 Puzzle8任务完成

**Comment by Kannnnng** [comment]
任务过期，清理关闭
