### ISSUE TITLE
袁晓梅任务反馈

### ISSUE THREAD

**Issue by raytaylorlin** [ITEC-ELWG/FE-Study#164]
### Blog任务反馈
- 点login按钮没法跳转到首页（下面HTML问题会解释）
- 首页article不符合两栏式布局，“学习笔记”那段文章主题被顶到下面去了，请自行查找两栏式布局的资料并修改
#### HTML问题
- a标签里面套`<input type="submit">`不合法，submit会阻止超链接的行为，二者只能择其一。请思考一下用a标签有什么缺陷，用`<input type="submit">`应该怎么写？
- 你之前提到的的label标签里面的for属性，是指点label应该focus到文本框上？for的属性应该指向id，也就是说你的文本框没有设置id
- 首页菜单栏，虽然用div和5个a标签没什么问题，但从语义上来说，用ul和5个li会更好
- `<a name="con1"></a>`是干什么用的？
- 首页`<footer>`里面套了太多层div了，完全没有必要
#### CSS问题
- 登录页css选择器很多都以`#slick-login`开头，例如`#slick-login input[type="text"]`。设想现在我要你再做一个注册页，里面要填“用户名”“密码”“再次输入密码”“年龄”“自我介绍”等等，那你这样写选择器样式是否能够复用？
- 登录页使用绝对居中实现的，请尝试改为块级元素水平居中
- 【进阶思考】为了让页面更加绚丽你用了一些CSS3的渐变颜色属性，那你肯定也发现了写一个CSS3属性要写5行来兼容其他浏览器，这样的CSS代码既冗长又难维护。设想现在设计师要你改各种颜色，5个5个改既麻烦又容易出错，有没有什么解决方法？

**Comment by raytaylorlin** [comment]
#166 

* `<button type="submit">`不知道是否符合标准，这个你再查一下，我粗略查到的是说在老的浏览器会有不一致的行为
* 【BUG】Login按钮只有点绿色文字才有效果，点白色部分没有效果；此外**`type="submit"`和a标签不要同时用！**
* #既然你要用CSS3动画那我就附带着评价一下# 不觉得正方块上升，到最后突然消失很突兀？

**Comment by raytaylorlin** [comment]
### Calculator任务反馈

#### 功能问题

* “%”号不起作用？（%就是直接除以100）
* 可以输入多个小数点
* 无法实现连续计算，即输入“2*3-”，输出“6”，再输入“1=”，输出“5”（参考市面上普通的计算器）

#### 代码问题

* **本任务请不要使用jQuery！**，在没学会原生js之前不要过度依赖库

**Comment by raytaylorlin** [comment]
#168 Blog任务完成

**Comment by NeoyeElf** [comment]
### Blog(PHP)任务反馈

* Mysql int类型的字段长度应该设置为11
* 当mysql连接出错时，直接显示了php错误
* 为什么没有使用conn.php文件，而是在login.php和register.php里面分别又去连接mysql
* 当输入错误的账号密码时，有php错误
* 注册时明文传递密码，注册成功时也有php错误
* 密码明文存储在mysql中
* 输入正确的账号，密码，无法正常登陆

**Comment by Kannnnng** [comment]
任务过期，清理关闭
