### ISSUE TITLE
孔思聪Blog任务反馈 

### ISSUE THREAD

**Issue by raytaylorlin** [ITEC-ELWG/FE-Study#88]
#### 代码问题
* id选择器使用过多，CSS原则上尽量不要使用id选择器（有的css lint工具甚至会对id选择器报警告）
* **这个不是问题**，代码规范不错，HTML结构也很清晰，值得表扬

#### 样式问题
* 登录页的按钮没有手型，首页的按钮只有文字有手型，这都不是一个正常按钮应该有的样式
* 首页背景图在小比例下会重复显示，不美观
* 说实话，两个页面实在是丑得令人发指，虽然实际工作不需要开发人员去设计，但我认为优秀的开发人员是必须要懂点设计的。建议你没事多看看优秀的设计多培养审美，必要时模仿一下，例如[优设网](http://www.uisdc.com/)

**Comment by kongsicong** [comment]
审美观确实很捉急，我会好好改进的

**Comment by raytaylorlin** [comment]
* 补充一下，`<button>`里面不要套`<a>`，通常的按钮，用`<a>`标签再加上一些圆角和hover的样式即可实现按钮（如Bootstrap就是这样实现），用`<button>`（需要去重置浏览器默认样式）或两者混用反而累赘

**Comment by raytaylorlin** [comment]
任务完成
