### ISSUE TITLE
曾祥意Blog任务反馈

### ISSUE THREAD

**Issue by raytaylorlin** [ITEC-ELWG/FE-Study#91]
任务功能达标，存在些许小问题。

#### 代码问题
* 代码中有少量tab和空格混用的情况
* 请统一使用4空格缩进
* 部分CSS冒号后无空格

#### CSS问题
* **首页居中布局和主题内容的两栏式布局，写法均不佳，可以在网上自行寻找下其他解决方案**
* 不要使用内敛CSS样式
* CSS类命名要统一，要么全用中划线形式，要么全用下划线形式，推荐**前者**

**Comment by wszxy** [comment]
内敛CSS样式是什么意思？布局问题我去查查。。

**Comment by raytaylorlin** [comment]
基础知识不扎实呀。。。`<img src="images/iconfont-aixin.png" style = "height: 28px; margin-right: 10px;">`的`style=...`就是内联CSS样式

**Comment by raytaylorlin** [comment]
任务完成
