### ISSUE TITLE
杜鹏Blog任务反馈

### ISSUE THREAD

**Issue by raytaylorlin** [ITEC-ELWG/FE-Study#92]
代码写得不错，而且还使用了CSS Reset，很值得其他组员参考学习。

代码存在一些小问题：
- `login-css.css`有空格和tab混用情况
- `<article>`和`<section>`语义理解不到位
- 很多样式由标签.类名控制（如a.note），多此一举。一般仅用类名控制样式就能满足多数需求

**Comment by Kannnnng** [comment]
任务过期，清理关闭
