### ISSUE TITLE
王远涵Blog任务反馈

### ISSUE THREAD

**Issue by raytaylorlin** [ITEC-ELWG/FE-Study#94]
**在不知道如何下手的情况下，请多参考别人的代码，以及利用好DevTools查看已有网站的代码**
#### 功能问题
- 登录页和首页均**没有实现居中布局**，需要重新修改
- 本次作业不需要绝对定位来布局，不要过度依赖absolute布局
- 不要使用table来布局！不要使用table来布局！不要使用table来布局！重要的事情说三遍！
#### HTML问题
- 登录页使用了两个`<form>`
- 内联了许多CSS样式
- 代码有很多多余的空行

**Comment by Kannnnng** [comment]
任务过期，清理关闭
